app = "set-up"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[[services]]
protocol = "tcp"
internal_port = 5432
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 100
soft_limit = 80

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
restart_limit = 0

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
restart_limit = 0
method = "get"
path = "/api/health"
protocol = "https"
