name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install dependencies
        working-directory: web
        run: yarn install

      - name: Build Vite.js project
        working-directory: web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: yarn run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 4a50610799c0ec3e2aa4253b7aa65f22
          projectName: set-up-client
          directory: dist
          workingDirectory: web
          wranglerVersion: "3"
